/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.stok_takip;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;

/**
 * @file stok_takip.java
 * @description Belirli bir şirketin stok durumunu kontrol eden program.
 * @assignment Bahar Dönemi 1.Proje
 * @date 17/05/2022
 * @author Muhammed Mesut Bahadır - muhammed.bahadir@stu.fsm.edu.tr
 */
public class Register extends javax.swing.JFrame {

    static String con = "jdbc:derby://localhost:1527/StokTakip";
    Connection connect = null;
    Statement state = null;
    ResultSet result = null;

    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Kayıt Ekranı");

    }

    //Connection yapısını birden fazla yerde kullanacağım için bunu bir metoda dönüştürmek istedim.
    //Bu metod sayesinde kodun ileriki safhalarında yazacağım kod fazlalıklarından kurtulmuş oldum.
    //Bu metod sayesinde database ile bağlantı sağlayabiliyorum.
    public Connection baglanti() {
        try {
            connect = DriverManager.getConnection(con);
        } catch (SQLException ex) {
            Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
        }

        return connect;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        turn = new javax.swing.JMenuItem();
        exit = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_username = new javax.swing.JTextField();
        txt_name = new javax.swing.JTextField();
        txt_surname = new javax.swing.JTextField();
        txt_password = new javax.swing.JPasswordField();
        txt_repassword = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        btn_KayitOl = new javax.swing.JButton();
        lbl_infoIcon = new javax.swing.JLabel();
        rbtn_female = new javax.swing.JRadioButton();
        rbtn_male = new javax.swing.JRadioButton();
        chb_kullaniciSoz = new javax.swing.JCheckBox();
        lbl_kullaniciSozlesmesi = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lbl_icon = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mi_renkDegis = new javax.swing.JMenuItem();
        mi_karanlikMod = new javax.swing.JMenuItem();
        mi_aydinlikMod = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        mi_girisEkraninaDon = new javax.swing.JMenuItem();
        mi_exit = new javax.swing.JMenuItem();

        turn.setText("Giriş ekranına dön.");
        turn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                turnActionPerformed(evt);
            }
        });
        jPopupMenu1.add(turn);

        exit.setText("Programdan çıkış.");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jPopupMenu1.add(exit);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setBackground(new java.awt.Color(255, 102, 102));
        jPanel1.setComponentPopupMenu(jPopupMenu1);

        jLabel2.setText("Kullanıcı Adı");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Ad");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Soyad");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Cinsiyet");

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Şifre");

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Şifre Tekrar");

        txt_username.setBackground(new java.awt.Color(255, 102, 102));
        txt_username.setForeground(new java.awt.Color(255, 255, 255));
        txt_username.setText("Kullanıcı adınızı giriniz...");
        txt_username.setBorder(null);
        txt_username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_usernameFocusGained(evt);
            }
        });

        txt_name.setBackground(new java.awt.Color(255, 102, 102));
        txt_name.setForeground(new java.awt.Color(255, 255, 255));
        txt_name.setText("Adınızı giriniz...");
        txt_name.setBorder(null);
        txt_name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_nameFocusGained(evt);
            }
        });

        txt_surname.setBackground(new java.awt.Color(255, 102, 102));
        txt_surname.setForeground(new java.awt.Color(255, 255, 255));
        txt_surname.setText("Soyadınızı giriniz...");
        txt_surname.setBorder(null);
        txt_surname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_surnameFocusGained(evt);
            }
        });

        txt_password.setBackground(new java.awt.Color(255, 102, 102));
        txt_password.setForeground(new java.awt.Color(255, 255, 255));
        txt_password.setText("jPasswordField1");
        txt_password.setBorder(null);
        txt_password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_passwordFocusGained(evt);
            }
        });

        txt_repassword.setBackground(new java.awt.Color(255, 102, 102));
        txt_repassword.setForeground(new java.awt.Color(255, 255, 255));
        txt_repassword.setText("jPasswordField2");
        txt_repassword.setBorder(null);
        txt_repassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_repasswordFocusGained(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));

        btn_KayitOl.setBackground(new java.awt.Color(255, 102, 102));
        btn_KayitOl.setForeground(new java.awt.Color(255, 255, 255));
        btn_KayitOl.setText("Kayıt Ol");
        btn_KayitOl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 102), 2));
        btn_KayitOl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_KayitOlActionPerformed(evt);
            }
        });

        lbl_infoIcon.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Documents\\NetBeansProjects\\Stok_Takip\\src\\main\\java\\icon\\warning.png")); // NOI18N
        lbl_infoIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_infoIconMouseClicked(evt);
            }
        });

        buttonGroup1.add(rbtn_female);
        rbtn_female.setForeground(new java.awt.Color(255, 255, 255));
        rbtn_female.setSelected(true);
        rbtn_female.setText("Kadın");

        buttonGroup1.add(rbtn_male);
        rbtn_male.setForeground(new java.awt.Color(255, 255, 255));
        rbtn_male.setText("Erkek");

        lbl_kullaniciSozlesmesi.setForeground(new java.awt.Color(255, 255, 255));
        lbl_kullaniciSozlesmesi.setText("Kullanıcı sözleşmesini kabul ediyorum.");
        lbl_kullaniciSozlesmesi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_kullaniciSozlesmesiMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_infoIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel2)
                        .addGap(12, 12, 12)
                        .addComponent(txt_username, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(txt_surname, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(txt_repassword, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_KayitOl, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(rbtn_female)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rbtn_male))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(chb_kullaniciSoz)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbl_kullaniciSozlesmesi))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txt_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txt_surname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_infoIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(7, 7, 7)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(txt_repassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(rbtn_female)
                        .addComponent(rbtn_male))
                    .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chb_kullaniciSoz)
                    .addComponent(lbl_kullaniciSozlesmesi))
                .addGap(11, 11, 11)
                .addComponent(btn_KayitOl, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);

        jPanel2.setBackground(new java.awt.Color(51, 0, 0));
        jPanel2.setComponentPopupMenu(jPopupMenu1);
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        lbl_icon.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Documents\\NetBeansProjects\\Stok_Takip\\src\\main\\java\\icon\\icons8_globe_120px.png")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(87, 123, 0, 0);
        jPanel2.add(lbl_icon, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 102));
        jLabel1.setText("KAYIT EKRANI ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 57, 142, 6);
        jPanel2.add(jLabel1, gridBagConstraints);

        getContentPane().add(jPanel2);

        jMenu1.setText("Menü");

        mi_renkDegis.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_J, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mi_renkDegis.setText("Sayfa Rengi Değiştir");
        mi_renkDegis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_renkDegisActionPerformed(evt);
            }
        });
        jMenu1.add(mi_renkDegis);

        mi_karanlikMod.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mi_karanlikMod.setText("Karanlık Mod");
        mi_karanlikMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_karanlikModActionPerformed(evt);
            }
        });
        jMenu1.add(mi_karanlikMod);

        mi_aydinlikMod.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mi_aydinlikMod.setText("Aydınlık Mod");
        mi_aydinlikMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_aydinlikModActionPerformed(evt);
            }
        });
        jMenu1.add(mi_aydinlikMod);
        jMenu1.add(jSeparator4);

        mi_girisEkraninaDon.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mi_girisEkraninaDon.setText("Giriş Ekranına Dön");
        mi_girisEkraninaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_girisEkraninaDonActionPerformed(evt);
            }
        });
        jMenu1.add(mi_girisEkraninaDon);

        mi_exit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mi_exit.setText("Exit");
        mi_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_exitActionPerformed(evt);
            }
        });
        jMenu1.add(mi_exit);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_usernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_usernameFocusGained
        // TODO add your handling code here:
        txt_username.setText("");
    }//GEN-LAST:event_txt_usernameFocusGained

    private void txt_nameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_nameFocusGained
        // TODO add your handling code here:
        txt_name.setText("");
    }//GEN-LAST:event_txt_nameFocusGained

    private void txt_surnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_surnameFocusGained
        // TODO add your handling code here:
        txt_surname.setText("");
    }//GEN-LAST:event_txt_surnameFocusGained

    private void txt_passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_passwordFocusGained
        // TODO add your handling code here:
        txt_password.setText("");
    }//GEN-LAST:event_txt_passwordFocusGained

    private void txt_repasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_repasswordFocusGained
        // TODO add your handling code here:
        txt_repassword.setText("");
    }//GEN-LAST:event_txt_repasswordFocusGained

    private void mi_renkDegisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_renkDegisActionPerformed
        // TODO add your handling code here:
        JColorChooser c = new JColorChooser();
        Color color = JColorChooser.showDialog(null, "Color", Color.yellow);
        jPanel2.setBackground(color);
    }//GEN-LAST:event_mi_renkDegisActionPerformed

    private void btn_KayitOlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_KayitOlActionPerformed
        // TODO add your handling code here:
        String username = "";
        String name = "";
        String surname = "";
        String password = "";
        String rePassword = "";

        //İlk başta textfield'ların dolu olup olmadığını kontrol ediyorum.
        if (txt_username.getText().isEmpty() || txt_username.getText().equals("Kullanıcı adınızı giriniz...")) {
            JOptionPane.showMessageDialog(null, "Lütfen kullanıcı adınızı giriniz.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        } else {
            username = txt_username.getText();
        }

        if (txt_name.getText().isEmpty() || txt_name.getText().equals("Adınızı giriniz...")) {
            JOptionPane.showMessageDialog(null, "Lütfen adınızı giriniz.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        } else {
            name = txt_name.getText();
        }

        if (txt_surname.getText().isEmpty() || txt_surname.getText().equals("Soyadınızı giriniz...")) {
            JOptionPane.showMessageDialog(null, "Lütfen soyadınızı giriniz.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        } else {
            surname = txt_surname.getText();
        }

        //Kullanıcının başta girdiği şifre ile tekrardan girdiği şifrenin kontrolonü sağlaması yanı sıra
        //girilen her iki şifrenin yazmış olduğum patterne uygun olup olmadığını kontrol eder.
        if (txt_password.getText().isEmpty() || txt_password.getText().equals("jPasswordField1")) {
            JOptionPane.showMessageDialog(null, "Lütfen şifrenizi doğru giriniz. ", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        } else {
            password = txt_password.getText();
            String pattern = "(?=.*[0-9])(?=.*[A-Z])(?=.*[_/.,#$%^&+=])(?=.*[a-z])(?=\\S+$).{6,}";
            Pattern p = Pattern.compile(pattern);
            Matcher m = p.matcher(password);

            if (!m.matches()) {
                JOptionPane.showMessageDialog(null, "Lütfen şifreyi kurallara uygun giriniz.", "Warning", JOptionPane.WARNING_MESSAGE);
                return;
            }
        }

        if (txt_repassword.getText().isEmpty() || txt_repassword.getText().equals("jPasswordField2")) {
            JOptionPane.showMessageDialog(null, "Lütfen şifrenizi tekrardan giriniz. ", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        } else {
            rePassword = txt_repassword.getText();
            if (!password.equals(rePassword)) {
                JOptionPane.showMessageDialog(null, "Lütfen şifrenizi doğru girdiğinizden emin olunuz.", "Warning", JOptionPane.WARNING_MESSAGE);
                return;
            } else {
                rePassword = password;
            }

        }

        String maleFemale = "";
        if (rbtn_male.isSelected()) {
            maleFemale = "Erkek";
        } else {
            maleFemale = "Kadın";
        }

        if (!chb_kullaniciSoz.isSelected()) {
            JOptionPane.showMessageDialog(null, "Lütfen kullanıcı sözleşmesini onaylayınız.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            connect = baglanti();
            state = connect.createStatement();
            result = state.executeQuery("SELECT * FROM app.users where KULLANICIADI ='" + username + "'");

            if (result.next()) {
                JOptionPane.showMessageDialog(null, "Bu kullanıcı zaten mevcut! Lütfen yeni bir kullanıcı girişi yapınız.", "Warning", JOptionPane.WARNING_MESSAGE);
            } else {
                connect.close();

                connect = baglanti();
                state = connect.createStatement();
                result = state.executeQuery("SELECT * FROM app.users");

                String query = "insert into app.users values('" + username + "',"
                        + "'" + name + "','" + surname + "','" + password + "','" + maleFemale + "')";

                state.executeUpdate(query);
                JOptionPane.showMessageDialog(null, "Başarıyla kayıt olundu.", "Warning", JOptionPane.WARNING_MESSAGE);
                this.dispose();
                Login l1 = new Login();
                l1.setVisible(true);
            }

        } catch (SQLException ex) {
            Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btn_KayitOlActionPerformed

    private void lbl_infoIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_infoIconMouseClicked
        //Şifre için belirlediğim kurallarım.
        JOptionPane.showMessageDialog(null, "Lütfen şifrenizi aşağıdaki kurallara uygun yazınız.\n 1)En az bir kere küçük harf kullanılmalıdır. \n 2)En az bir kere küçük harf kullanılmalıdır. \n"
                + " 3)(?=.*[_/.,#$%^&+=]) özel bir karakterlerinden en az bir tanesini içermelidir.\n"
                + " 4)En az 6 karakter içermelidir.", "Warning", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_lbl_infoIconMouseClicked

    private void mi_karanlikModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_karanlikModActionPerformed
        // TODO add your handling code here:
        jPanel1.setBackground(new Color(51, 51, 51));
        jPanel2.setBackground(new Color(153, 153, 153));
        txt_name.setBackground(new Color(51, 51, 51));
        txt_password.setBackground(new Color(51, 51, 51));
        txt_repassword.setBackground(new Color(51, 51, 51));
        txt_surname.setBackground(new Color(51, 51, 51));
        txt_username.setBackground(new Color(51, 51, 51));
        btn_KayitOl.setBackground(new Color(51, 51, 51));
        btn_KayitOl.setBorder(null);
        jLabel1.setForeground(new Color(51, 51, 51));
        ImageIcon icon = new ImageIcon("C:\\Users\\ASUS\\Documents\\NetBeansProjects\\Stok_Takip\\src\\main\\java\\icon\\globeGray.png");
        lbl_icon.setIcon(icon);
    }//GEN-LAST:event_mi_karanlikModActionPerformed

    private void mi_aydinlikModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_aydinlikModActionPerformed
        // TODO add your handling code here:
        jPanel1.setBackground(new Color(255, 102, 102));
        jPanel2.setBackground(new Color(51, 0, 0));
        txt_name.setBackground(new Color(255, 102, 102));
        txt_password.setBackground(new Color(255, 102, 102));
        txt_repassword.setBackground(new Color(255, 102, 102));
        txt_surname.setBackground(new Color(255, 102, 102));
        txt_username.setBackground(new Color(255, 102, 102));
        btn_KayitOl.setBackground(new Color(255, 102, 102));
        jLabel1.setForeground(new Color(255, 102, 102));
        ImageIcon icon = new ImageIcon("C:\\Users\\ASUS\\Documents\\NetBeansProjects\\Stok_Takip\\src\\main\\java\\icon\\icons8_globe_120px.png");
        lbl_icon.setIcon(icon);
    }//GEN-LAST:event_mi_aydinlikModActionPerformed

    private void mi_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_exitActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_mi_exitActionPerformed

    private void turnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_turnActionPerformed
        // TODO add your handling code here:
        Login l = new Login();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_turnActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        this.dispose();
    }//GEN-LAST:event_exitActionPerformed

    private void mi_girisEkraninaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_girisEkraninaDonActionPerformed
        // TODO add your handling code here:
        Login l = new Login();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mi_girisEkraninaDonActionPerformed

    private void lbl_kullaniciSozlesmesiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_kullaniciSozlesmesiMouseClicked
        JOptionPane.showMessageDialog(null, "Şirket tarafından tarafınıza verilen bu erişim hakkını ve şirkete ait verilerin 3.kişilerle paylaşılmayıp gizlilik \n"
                + " ilkesine bağlı kalınılması gerekmektedir. Bağlı olduğunuz yasalara göre sözleşme imzalama hakkına,\n"
                + " yetkisine ve hukuki ehliyetine sahip ve 18 yaşın üzerinde olduğunuzu, bu sözleşmeyi okuduğunuzu,\n anladığınızı ve sözleşmede yazan şartlarla bağlı olduğunuzu kabul etmiş sayılırsınız. Aksi takdirde, \n"
                + " gerekilen hukuki adımlar bizzat şirketimiz tarafından atılacaktır. ", "Kullanıcı Sözleşmesi", JOptionPane.WARNING_MESSAGE);

    }//GEN-LAST:event_lbl_kullaniciSozlesmesiMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_KayitOl;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox chb_kullaniciSoz;
    private javax.swing.JMenuItem exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel lbl_icon;
    private javax.swing.JLabel lbl_infoIcon;
    private javax.swing.JLabel lbl_kullaniciSozlesmesi;
    private javax.swing.JMenuItem mi_aydinlikMod;
    private javax.swing.JMenuItem mi_exit;
    private javax.swing.JMenuItem mi_girisEkraninaDon;
    private javax.swing.JMenuItem mi_karanlikMod;
    private javax.swing.JMenuItem mi_renkDegis;
    private javax.swing.JRadioButton rbtn_female;
    private javax.swing.JRadioButton rbtn_male;
    private javax.swing.JMenuItem turn;
    private javax.swing.JTextField txt_name;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JPasswordField txt_repassword;
    private javax.swing.JTextField txt_surname;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
