/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.stok_takip;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 * @file stok_takip.java
 * @description Belirli bir şirketin stok durumunu kontrol eden program.
 * @assignment Bahar Dönemi 1.Proje
 * @date 17/05/2022
 * @author Muhammed Mesut Bahadır - muhammed.bahadir@stu.fsm.edu.tr
 */
public class UrunEkle extends javax.swing.JFrame {

    private static UrunEkle obj = null;
    static String con = "jdbc:derby://localhost:1527/StokTakip";
    Connection connect = null;
    Statement state = null;
    ResultSet result = null;
    DefaultTableModel model;

    /**
     * Creates new form UrunEkle
     */
    public UrunEkle() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Ürün Ekleme Ekranı");
        model = (DefaultTableModel) jTable1.getModel();

    }
    //Connection yapısını birden fazla yerde kullanacağım için bunu bir metoda dönüştürmek istedim.
    //Bu metod sayesinde kodun ileriki safhalarında yazacağım kod fazlalıklarından kurtulmuş oldum.
    //Bu metod sayesinde database ile bağlantı sağlayabiliyorum.

    public Connection baglanti() {
        try {
            connect = DriverManager.getConnection(con);
        } catch (SQLException ex) {
            Logger.getLogger(UrunEkle.class.getName()).log(Level.SEVERE, null, ex);
        }

        return connect;
    }

    //Ürünler isimli bir class açıp, veritabanına eklemek istediğim ürüne ait bilgileri burada da oluşturup
    //birden fazla kısımda kullanma ihtimalime karşın kod fazlalığından kaçınmak amaçlı bu metodu yazdım.
    //Bu metodu databaseden aldığım verileri Ürünler class'ı aracılığıyla tablo oluşturmak için kullandım.
    public ArrayList<Urunler> urunler(String query) {
        ArrayList<Urunler> urunlerList = new ArrayList<>();
        try {
            connect = baglanti();
            state = connect.createStatement();
            result = state.executeQuery(query);
            Urunler urun;
            while (result.next()) {
                urun = new Urunler(result.getString("urunId"), result.getString("urunAd"), result.getString("urunGrubu"), result.getString("urunAdedi"), result.getString("urunTarih"), result.getString("urunFiyat"));
                urunlerList.add(urun);
            }
            connect.close();
            state.close();
        } catch (SQLException ex) {
            Logger.getLogger(UrunEkle.class.getName()).log(Level.SEVERE, null, ex);
        }

        return urunlerList;
    }

    //Birden fazla tablo oluşturma ihtimalime karşın bu metodu yazdım. Üst taraftaki metoddan aldığım 
    //aldığım bilgileri tabloya aktarmamı sağlayan metoddur.
    public void showTable(String q) {
        ArrayList<Urunler> list = urunler(q);

        Object[] row = new Object[6];
        for (int i = 0; i < list.size(); i++) {
            row[0] = list.get(i).getUrunId();
            row[1] = list.get(i).getUrunAd();
            row[2] = list.get(i).getUrunGrubu();
            row[3] = list.get(i).getUrunAdedi();
            row[5] = list.get(i).getUrunTarihi();
            row[4] = list.get(i).getUrunFiyati();

            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        txt_urunAdi = new javax.swing.JTextField();
        txt_urunGrubu = new javax.swing.JTextField();
        spn_adet = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cmb_gun = new javax.swing.JComboBox<>();
        cmb_ay = new javax.swing.JComboBox<>();
        cmb_yil = new javax.swing.JComboBox<>();
        btn_ekle = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txt_fiyatBilgi = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txt_search = new javax.swing.JTextField();
        btn_listeGuncelle = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ürün Ekleme");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Ürün ID");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Ürün Adı");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tarih");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Ürün Grubu");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Ürün Adeti");

        txt_id.setBackground(new java.awt.Color(153, 153, 153));
        txt_id.setMinimumSize(new java.awt.Dimension(70, 22));
        txt_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_idKeyTyped(evt);
            }
        });

        txt_urunAdi.setBackground(new java.awt.Color(153, 153, 153));
        txt_urunAdi.setMinimumSize(new java.awt.Dimension(70, 22));

        txt_urunGrubu.setBackground(new java.awt.Color(153, 153, 153));
        txt_urunGrubu.setMinimumSize(new java.awt.Dimension(70, 22));

        spn_adet.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        spn_adet.setMinimumSize(new java.awt.Dimension(60, 22));
        spn_adet.setOpaque(true);
        spn_adet.setPreferredSize(new java.awt.Dimension(60, 22));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Gün");

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Ay");

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Yıl");

        cmb_gun.setBackground(new java.awt.Color(0, 0, 0));
        cmb_gun.setForeground(new java.awt.Color(255, 255, 255));
        cmb_gun.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        cmb_ay.setBackground(new java.awt.Color(0, 0, 0));
        cmb_ay.setForeground(new java.awt.Color(255, 255, 255));
        cmb_ay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));

        cmb_yil.setBackground(new java.awt.Color(0, 0, 0));
        cmb_yil.setForeground(new java.awt.Color(255, 255, 255));
        cmb_yil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2022", "2021", "2020", "2019", "2018", "2017", "2016", "2015" }));

        btn_ekle.setBackground(new java.awt.Color(0, 0, 0));
        btn_ekle.setForeground(new java.awt.Color(255, 255, 255));
        btn_ekle.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Documents\\NetBeansProjects\\Stok_Takip\\src\\main\\java\\icon\\plus.png")); // NOI18N
        btn_ekle.setText("Ekle");
        btn_ekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ekleActionPerformed(evt);
            }
        });

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Ürün Fiyatı");

        txt_fiyatBilgi.setBackground(new java.awt.Color(153, 153, 153));
        txt_fiyatBilgi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_fiyatBilgiKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_ekle, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(43, 43, 43)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(82, 82, 82)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txt_urunAdi, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txt_urunGrubu, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                                        .addComponent(txt_fiyatBilgi))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cmb_gun, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmb_ay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cmb_yil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(spn_adet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel12)))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_urunAdi, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_urunGrubu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txt_fiyatBilgi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(spn_adet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb_gun, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmb_ay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmb_yil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_ekle, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Documents\\NetBeansProjects\\Stok_Takip\\src\\main\\java\\icon\\magnifying-glass.png")); // NOI18N

        txt_search.setBackground(new java.awt.Color(153, 153, 153));
        txt_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_searchKeyTyped(evt);
            }
        });

        btn_listeGuncelle.setBackground(new java.awt.Color(153, 153, 153));
        btn_listeGuncelle.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Documents\\NetBeansProjects\\Stok_Takip\\src\\main\\java\\icon\\refresh.png")); // NOI18N
        btn_listeGuncelle.setText("Listeyi Güncelle");
        btn_listeGuncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_listeGuncelleActionPerformed(evt);
            }
        });

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Ürün ID");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btn_listeGuncelle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_listeGuncelle)
                            .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ürün ID", "Ürün Adı", "Ürün Grubu", "Ürün Adeti", "Ürün Fiyatı (TL)", "Güncelleme Tarihi"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 679, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_searchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyTyped
        //Kullanıcının Id kismina rakam harici başka bir şey yazmamasını sağlar.
        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_searchKeyTyped

    private void txt_idKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_idKeyTyped
        //Kullanıcının Id kismina rakam harici başka bir şey yazmamasını sağlar.
        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_idKeyTyped

    private void btn_ekleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ekleActionPerformed
        String id = "";
        String ad = "";
        String urunGrup = "";
        int adet = 0;
        String tarih = "";
        String fiyat = "";

        //İlk başta textfield'ların dolu olup olmadığını kontrol ediyorum ve id kısmında
        //patternim ile regex kontrolünü sağladım.
        if (txt_id.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Lütfen ürün id'sini giriniz.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        } else {
            id = txt_id.getText();
            String pattern = "[0-9]+";
            Pattern p = Pattern.compile(pattern);
            Matcher m = p.matcher(id);

            if (!m.matches()) {
                JOptionPane.showMessageDialog(null, "Lütfen şifreyi kurallara uygun giriniz.", "Warning", JOptionPane.WARNING_MESSAGE);
                return;
            }
        }

        if (txt_urunAdi.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Lütfen ürün adını giriniz.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        } else {
            ad = txt_urunAdi.getText();
        }

        if (txt_urunGrubu.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Lütfen ürün grubunu giriniz.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        } else {
            urunGrup = txt_urunGrubu.getText();
        }

        if (txt_fiyatBilgi.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Lütfen ürün fiyatını giriniz.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        } else {
            fiyat = txt_fiyatBilgi.getText();
        }

        adet = (int) spn_adet.getValue();
        String adetTotal = adet + "";

        String yil = cmb_yil.getSelectedItem().toString();
        String gun = cmb_gun.getSelectedItem().toString();
        String ay = cmb_ay.getSelectedItem().toString();
        //Aşağıda yazmış olduğum metod ile tarihin kontorlünü sağlıyorum. Akış dılı tarih girildiğinde
        //aşağıdaki hata mesajı verilir.(Örneğin 29.02.2017 olmayacağını gösterir.) 
        if (!(tarihHesap(gun, ay, yil))) {
            JOptionPane.showMessageDialog(null, "Hatalı tarih girişi yaptınız.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        tarih = gun + "/" + ay + "/" + yil;

        try {

            connect = baglanti();
            state = connect.createStatement();
            result = state.executeQuery("SELECT * FROM app.urunler where URUNID='" + id + "'");

            //Veritabanındaki satır sayısı 0'dan büyük olduğu ve ürünün id'si başka bir ürünün id'si ile eşleşmediği
            //sürece ürünü veritabanına ekler. Veritabanındaki satır sayısı 0'sa yani içi boş ise bunu else kısmı
            //ile doğrudan ekler. Ürün id'sinin aynı olması dahilinde ürünün zaten var olduğunu yönünde uyarı verir.
            if (result.next()) {
                JOptionPane.showMessageDialog(null, "Bu ürün zaten mevcut! Lütfen yeni bir ürün giriniz. \n(Varolan ürünün miktarında değişiklik yapmak için lütfen Ürün Güncelle ekranınını kullanınız. )", "Warning", JOptionPane.WARNING_MESSAGE);
                return;
            } else {
                connect.close();

                connect = baglanti();
                state = connect.createStatement();
                result = state.executeQuery("SELECT * FROM app.urunler");

                //Bu kısımdaki query veritabanımdaki ürünler tablosuna ürün eklenmesini sağlayacak.
                String query = "insert into app.urunler values('" + id + "',"
                        + "'" + ad + "','" + urunGrup + "','" + adetTotal + "','" + tarih + "','" + fiyat + "')";

                state.executeUpdate(query);

                //Connection'u close'layıp listenin tekrardan başından alınmasını sağlamış oluyorum.
                connect.close();
                state.close();

                connect = baglanti();
                state = connect.createStatement();
                //Buradaki query ise veriler kısmında eklenen ürünlerin verisini tutmak istediğim için
                //veritabanındaki eklenen ürünler tablosuna gerekli veriyi ekler.
                String query2 = "insert into app.eklenenurunler values('" + id + "',"
                        + "'" + ad + "','" + urunGrup + "','" + adetTotal + "','" + tarih + "','" + fiyat + "')";
                state.executeUpdate(query2);
                JOptionPane.showMessageDialog(null, "Ürün başarıyla kaydedildi.", "Warning", JOptionPane.WARNING_MESSAGE);
                txt_id.setText("");
                txt_search.setText("");
                txt_urunAdi.setText("");
                txt_urunGrubu.setText("");
                txt_fiyatBilgi.setText("");
                spn_adet.setValue(1);
                cmb_ay.setSelectedIndex(0);
                cmb_gun.setSelectedIndex(0);
                cmb_yil.setSelectedIndex(0);
                return;

            }

        } catch (SQLException ex) {
            Logger.getLogger(UrunEkle.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_btn_ekleActionPerformed

    private void btn_listeGuncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_listeGuncelleActionPerformed
        model.setRowCount(0);
        if (txt_search.getText().isEmpty()) {
            String query = "SELECT * FROM app.urunler";
            showTable(query);
        } else {
            String query2 = "SELECT * FROM app.urunler WHERE urunId LIKE '%" + txt_search.getText() + "%'";
            showTable(query2);
        }
    }//GEN-LAST:event_btn_listeGuncelleActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        txt_id.setText("");
        txt_search.setText("");
        txt_urunAdi.setText("");
        txt_urunGrubu.setText("");
        txt_fiyatBilgi.setText("");
        spn_adet.setValue(1);
        cmb_ay.setSelectedIndex(0);
        cmb_gun.setSelectedIndex(0);
        cmb_yil.setSelectedIndex(0);
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    private void txt_fiyatBilgiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_fiyatBilgiKeyTyped
        //Kullanıcının Id kismina rakam harici başka bir şey yazmamasını sağlar.
        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_fiyatBilgiKeyTyped
    public static UrunEkle getObj() {
        //Main kısmında belirttiğim bir panelin birden fazla açılmasını engellemek
        //amaçlı yazdığım metot.
        if (obj == null) {
            obj = new UrunEkle();
        }
        return obj;
    }

    //Yukarıda belirttiğim gibi kullanıcının girmiş olduğu tarih bilgisinin
    //doğruluğunu kontrol edip ona göre boolean true veya false dönen metoddur.
    public boolean tarihHesap(String gun, String ay, String yil) {
        boolean dogruTarih = true;
        int yil2 = Integer.parseInt(yil);
        int gun2 = Integer.parseInt(gun);

        switch (ay) {
            case "02":
                if (((yil2 % 4 == 0) && !(yil2 % 100 == 0)) || (yil2 % 400 == 0)) {
                    if (gun2 == 30 || gun2 == 31) {
                        dogruTarih = false;
                    } else {
                        dogruTarih = true;
                    }

                } else {
                    if (gun2 == 29 || gun2 == 30 || gun2 == 31) {
                        dogruTarih = false;
                    } else {
                        dogruTarih = true;
                    }

                }
                break;

            case "04":
                if (gun2 == 31) {
                    dogruTarih = false;
                } else {
                    dogruTarih = true;
                }
                break;

            case "06":
                if (gun2 == 31) {
                    dogruTarih = false;
                } else {
                    dogruTarih = true;
                }
                break;
            case "09":
                if (gun2 == 31) {
                    dogruTarih = false;
                } else {
                    dogruTarih = true;
                }
                break;

            case "11":
                if (gun2 == 31) {
                    dogruTarih = false;
                } else {
                    dogruTarih = true;
                }
                break;

        }
        return dogruTarih;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UrunEkle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UrunEkle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UrunEkle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UrunEkle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UrunEkle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ekle;
    private javax.swing.JButton btn_listeGuncelle;
    private javax.swing.JComboBox<String> cmb_ay;
    private javax.swing.JComboBox<String> cmb_gun;
    private javax.swing.JComboBox<String> cmb_yil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JSpinner spn_adet;
    private javax.swing.JTextField txt_fiyatBilgi;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_search;
    private javax.swing.JTextField txt_urunAdi;
    private javax.swing.JTextField txt_urunGrubu;
    // End of variables declaration//GEN-END:variables
}
